---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zram-csi
provisioner: zram.csi.k8s.io
parameters:
  "csi.storage.k8s.io/fstype": "ext4"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer